export const navGroups = [
  {
    group: 'Main',
    module: 'main',
    theme: 'slate',
    icon: 'LayoutDashboard',
    items: [
      { label: 'Dashboard', href: '/dashboard', icon: 'LayoutDashboard' },
    ],
  },
  {
    group: 'Financial',
    module: 'financial',
    theme: 'emerald',
    icon: 'DollarSign',
    items: [
      { label: 'Chart of Accounts', href: '/financial/coa', icon: 'BookOpen' },
      { label: 'Journal Entries', href: '/financial/journal', icon: 'FileText' },
      { label: 'General Ledger', href: '/financial/ledger', icon: 'Book' },
      { label: 'Trial Balance', href: '/financial/trial-balance', icon: 'Scale' },
      { label: 'Accounts Receivable', href: '/financial/ar', icon: 'Receipt' },
      { label: 'Sales Journal', href: '/financial/sales-journal', icon: 'Book' },
      { label: 'Sales Ledger', href: '/financial/sales-ledger', icon: 'Receipt' },
      { label: 'Accounts Payable', href: '/financial/ap', icon: 'CreditCard' },
      { label: 'Purchases Journal', href: '/financial/purchases-journal', icon: 'FileText' },
      { label: 'Purchases Ledger', href: '/financial/purchases-ledger', icon: 'BookOpen' },
      { label: 'Cashbook', href: '/financial/cashbook', icon: 'Wallet' },
      { label: 'Income Statement', href: '/financial/income-statement', icon: 'TrendingUp' },
      { label: 'Cashflow Statement', href: '/financial/cashflow-statement', icon: 'ArrowLeftRight' },
      { label: 'Balance Sheet', href: '/financial/balance-sheet', icon: 'Scale' },
      { label: 'Statement of Changes in Equity', href: '/financial/statement-of-changes-in-equity', icon: 'LineChart' },
      { label: 'Age Analysis', href: '/financial/age-analysis', icon: 'BarChart3' },
      { label: 'Multi-Currency VAT', href: '/financial/multicurrency-vat-reporting', icon: 'Percent' },
      { label: 'Tax Engine', href: '/tax', icon: 'Percent' },
      { label: 'Reports & Analytics', href: '/financial/reports', icon: 'FileBarChart' },
    ],
  },
  {
    group: 'Sales & Marketing',
    module: 'sales',
    theme: 'orange',
    icon: 'TrendingUp',
    items: [
      { label: 'Dashboard', href: '/sales/dashboard', icon: 'LayoutDashboard' },
      { label: 'Quotations', href: '/sales/quotations', icon: 'FileText' },
    ],
  },
  {
    group: 'CRM',
    module: 'crm',
    theme: 'purple',
    icon: 'Users',
    items: [
      { label: 'Customers', href: '/crm/customers', icon: 'Users' },
      { label: 'Leads', href: '/crm/leads', icon: 'Target' },
      { label: 'Suppliers', href: '/suppliers', icon: 'Building2' },
      { label: 'Loyalty Program', href: '/crm/loyalty', icon: 'Award' },
      { label: 'Big Spenders', href: '/crm/spenders', icon: 'Crown' },
      { label: 'Resellers', href: '/crm/resellers', icon: 'Handshake' },
      { label: 'Reports & Analytics', href: '/crm/reports', icon: 'FileBarChart' },
    ],
  },
  {
    group: 'Inventory',
    module: 'inventory',
    theme: 'sky',
    icon: 'Package',
    items: [
      { label: 'Dashboard', href: '/inventory/dashboard', icon: 'LayoutDashboard' },
      { label: 'Products', href: '/inventory/products', icon: 'Package' },
      { label: 'Customer Orders', href: '/inventory/customer-orders', icon: 'ShoppingCart' },
      { label: 'Sales Management', href: '/inventory/sales-management', icon: 'BarChart3' },
      { label: 'Sales Forecasting', href: '/inventory/sales-forecasting', icon: 'TrendingUp' },
      { label: 'Inventory Overview', href: '/inventory/overview', icon: 'FolderTree' },
      { label: 'Branch Orders', href: '/inventory/branch-orders', icon: 'Store' },
      { label: 'Seasonality', href: '/inventory/seasonality', icon: 'Clock' },
      { label: 'Reports', href: '/inventory/reports', icon: 'FileBarChart' },
    ],
  },
  {
    group: 'Purchasing',
    module: 'purchasing',
    theme: 'teal',
    icon: 'ShoppingCart',
    items: [
      { label: 'Requisitions', href: '/purchasing/requisitions', icon: 'ClipboardList' },
      { label: 'Reports & Analytics', href: '/purchasing/reports', icon: 'FileBarChart' },
    ],
  },
  {
    group: 'Warehouse',
    module: 'warehouse',
    theme: 'indigo',
    icon: 'Warehouse',
    items: [
      { label: 'Dashboard', href: '/warehouse', icon: 'LayoutDashboard' },
      { label: 'Warehouses', href: '/warehouse/warehouses', icon: 'Warehouse' },
      { label: 'Locations', href: '/warehouse/branches', icon: 'Building2' },
      { label: 'Back Order Mgt', href: '/warehouse/back-orders', icon: 'AlertTriangle' },
      { label: 'Goods Receiving', href: '/inventory/goods-receipts', icon: 'ClipboardCheck' },
      { label: 'Branch Orders', href: '/warehouse/branch-orders', icon: 'Store' },
      { label: 'L99 Discrepancies', href: '/warehouse/l99-investigation', icon: 'AlertTriangle' },
      { label: 'Stock Transfers', href: '/warehouse/stock-transfers', icon: 'ArrowLeftRight' },
      { label: 'Storage Locations', href: '/warehouse/storage-locations', icon: 'Package' },
      { label: 'Cycle Counts', href: '/warehouse/cycle-counts', icon: 'ClipboardList' },
      { label: 'Reports', href: '/warehouse/reports', icon: 'FileBarChart' },
    ],
  },
  {
    group: 'POS',
    module: 'pos',
    theme: 'violet',
    icon: 'Store',
    items: [
      { label: 'POS Terminal', href: '/pos', icon: 'ShoppingCart' },
      { label: 'Sessions', href: '/pos/sessions', icon: 'Receipt' },
      { label: 'History', href: '/pos/history', icon: 'FileText' },
      { label: 'Invoice Journal', href: '/pos/journal', icon: 'Book' },
      { label: 'Z Reports (EOD)', href: '/pos/reports/z-reports', icon: 'FileText' },
      { label: 'Variances', href: '/pos/reports/variances', icon: 'AlertTriangle' },
      { label: 'Branch Orders', href: '/inventory/branch-orders', icon: 'Store' },
      { label: 'Reports & Analytics', href: '/pos/reports', icon: 'FileBarChart' },
    ],
  },
  {
    group: 'Workshop',
    module: 'workshop',
    theme: 'rose',
    icon: 'Wrench',
    items: [
      { label: 'Equipment', href: '/workshop/equipment', icon: 'Wrench' },
      { label: 'Work Orders', href: '/workshop/work-orders', icon: 'ClipboardList' },
      { label: 'Reports & Analytics', href: '/workshop/reports', icon: 'FileBarChart' },
    ],
  },
  {
    group: 'Fleet & Fuel',
    module: 'fleet',
    theme: 'cyan',
    icon: 'Truck',
    items: [
      { label: 'Vehicles & Tracking', href: '/fleet/vehicles', icon: 'Truck' },
      { label: 'Fuel Requisitions', href: '/fleet/requisitions', icon: 'ClipboardList' },
      { label: 'Prepaid Fuel', href: '/fleet/prepaid', icon: 'CreditCard' },
      { label: 'Hauling Trips', href: '/fleet/hauling', icon: 'ArrowLeftRight' },
      { label: 'Reports & Analytics', href: '/fleet/reports', icon: 'FileBarChart' },
    ],
  },
  {
    group: 'FDMS',
    module: 'fdms',
    theme: 'fuchsia',
    icon: 'QrCode',
    items: [
      { label: 'Fiscalisation', href: '/fdms', icon: 'QrCode' },
      { label: 'Reports & Analytics', href: '/fdms/reports', icon: 'FileBarChart' },
    ],
  },
  {
    group: 'Messaging',
    module: 'messaging',
    theme: 'pink',
    icon: 'MessageCircle',
    items: [
      { label: 'Messages', href: '/messaging', icon: 'MessageCircle' },
    ],
  },
  {
    group: 'Reports',
    module: 'reports',
    theme: 'amber',
    icon: 'BarChart3',
    items: [
      { label: 'Reports & Analytics', href: '/reports', icon: 'BarChart3' },
    ],
  },
  {
    group: 'Admin',
    module: 'admin',
    theme: 'red',
    icon: 'Shield',
    items: [
      { label: 'Users', href: '/admin/users', icon: 'Shield' },
      { label: 'Branches', href: '/admin/branches', icon: 'Building2' },
      { label: 'Settings', href: '/admin/settings', icon: 'Settings' },
      { label: 'Audit Trail', href: '/admin/audit', icon: 'ScrollText' },
    ],
  },
  {
    group: 'Projects',
    module: 'projects',
    theme: 'mine-blue',
    icon: 'Briefcase',
    items: [
      { label: 'Dashboard', href: '/projects/dashboard', icon: 'LayoutDashboard' },
      { label: 'All Projects', href: '/projects', icon: 'Briefcase' },
      { label: 'Reports & Analytics', href: '/projects/reports', icon: 'BarChart3' },
    ],
  },
  {
    group: 'Documents',
    module: 'documents',
    theme: 'sky',
    icon: 'FolderTree',
    items: [
      { label: 'Repository', href: '/documents', icon: 'FolderTree' },
      { label: 'Recent Files', href: '/documents/recent', icon: 'Clock' },
    ],
  },
];
