'use client';

import { useState, useEffect } from 'react';
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { FileText, Printer, ArrowLeft, Building2, User, Clock, CalendarDays, Receipt } from 'lucide-react';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useReactToPrint } from 'react-to-print';
import { useRef } from 'react';

export default function ZReportDetailPage() {
  const params = useParams();
  const id = params.id as string;
  const [report, setReport] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const printRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const fetchReport = async () => {
      try {
        const res = await fetch(`/api/pos/reports/z-reports/${id}`);
        if (res.ok) {
          const data = await res.json();
          setReport(data);
        }
      } catch (e) {
        console.error(e);
      }
      setLoading(false);
    };
    fetchReport();
  }, [id]);

  const handlePrint = useReactToPrint({
    contentRef: printRef,
    documentTitle: `Z-Report-${report?.reportNumber || 'Doc'}`,
  });

  if (loading) {
    return (
      <div className="flex justify-center items-center h-64">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-mine-blue-600"></div>
      </div>
    );
  }

  if (!report) {
    return (
      <div className="text-center py-12">
        <Receipt className="mx-auto h-12 w-12 text-slate-300 mb-4" />
        <h3 className="text-lg font-medium text-slate-900">Report Not Found</h3>
        <p className="text-slate-500 mt-2">The Z Report you are looking for does not exist.</p>
        <Link href="/pos/reports/z-reports" className="mt-4 inline-block text-mine-blue-600 hover:underline">
          &larr; Back to Reports
        </Link>
      </div>
    );
  }

  return (
    <div className="space-y-6 max-w-3xl mx-auto">
      <div className="flex items-center justify-between">
        <Link href="/pos/reports/z-reports">
          <Button variant="ghost" className="text-slate-600 hover:text-slate-900">
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Z Reports
          </Button>
        </Link>
        <Button onClick={handlePrint} className="bg-slate-800 hover:bg-slate-900">
          <Printer className="mr-2 h-4 w-4" />
          Print Report
        </Button>
      </div>

      <Card className="shadow-lg">
        {/* Printable Area */}
        <div ref={printRef} className="bg-white p-8 sm:p-12 text-slate-800 rounded-lg">
          {/* Header */}
          <div className="relative text-center border-b border-dashed border-slate-300 pb-6 mb-6">
            <div className="absolute top-0 left-0">
              <img src="/logo.png" alt="Mineazy Logo" className="h-12 object-contain" />
            </div>
            <div className="space-y-2">
              <h1 className="text-3xl font-bold tracking-tighter uppercase">Z-Report</h1>
              <p className="text-sm font-mono text-slate-500 tracking-widest">{report.reportNumber}</p>
              {report.branch && (
                <div className="flex items-center justify-center text-sm font-medium text-slate-600 mt-2">
                  <Building2 className="mr-1.5 h-4 w-4" />
                  {report.branch.name}
                </div>
              )}
            </div>
          </div>

          {/* Meta Info Grid */}
          <div className="grid grid-cols-2 gap-y-4 gap-x-8 mb-8 text-sm">
            <div>
              <span className="text-slate-500 block text-xs uppercase tracking-wider font-semibold mb-1">Generated By</span>
              <div className="flex items-center font-medium">
                <User className="mr-2 h-4 w-4 text-slate-400" />
                {report.generatedBy}
              </div>
            </div>
            <div>
              <span className="text-slate-500 block text-xs uppercase tracking-wider font-semibold mb-1">Generated At</span>
              <div className="flex items-center font-medium">
                <CalendarDays className="mr-2 h-4 w-4 text-slate-400" />
                {new Date(report.generatedAt).toLocaleString()}
              </div>
            </div>
            <div>
              <span className="text-slate-500 block text-xs uppercase tracking-wider font-semibold mb-1">Session Opened</span>
              <div className="flex items-center font-medium">
                <Clock className="mr-2 h-4 w-4 text-emerald-500" />
                {new Date(report.openedAt).toLocaleString()}
              </div>
            </div>
            <div>
              <span className="text-slate-500 block text-xs uppercase tracking-wider font-semibold mb-1">Session Closed</span>
              <div className="flex items-center font-medium">
                <Clock className="mr-2 h-4 w-4 text-red-500" />
                {new Date(report.closedAt).toLocaleString()}
              </div>
            </div>
          </div>

          {/* Financial Summary */}
          <div className="space-y-6">
            {/* Sales Summary */}
            <div>
              <h3 className="text-lg font-bold border-b border-slate-200 pb-2 mb-3">Sales Summary</h3>
              <div className="space-y-2">
                <div className="flex justify-between text-sm">
                  <span className="text-slate-600">Total Sales (Gross)</span>
                  <span className="font-mono">${(Number(report.totalSales) + Number(report.totalDiscounts)).toFixed(2)}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-slate-600">Total Tax Collected</span>
                  <span className="font-mono">${Number(report.totalTax).toFixed(2)}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-slate-600">Total Discounts</span>
                  <span className="font-mono">-${Number(report.totalDiscounts).toFixed(2)}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-slate-600">Voided Transactions (Refunds)</span>
                  <span className="font-mono">-${Number(report.totalRefunds).toFixed(2)}</span>
                </div>
                <div className="flex justify-between font-bold text-base pt-2 border-t border-slate-100">
                  <span>Net Sales</span>
                  <span className="font-mono">${Number(report.totalSales).toFixed(2)}</span>
                </div>
              </div>
            </div>

            {/* Payment Tenders */}
            <div>
              <h3 className="text-lg font-bold border-b border-slate-200 pb-2 mb-3">Tender Breakdown</h3>
              <div className="space-y-2">
                <div className="flex justify-between text-sm">
                  <span className="text-slate-600">Cash</span>
                  <span className="font-mono">${Number(report.cashSales).toFixed(2)}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-slate-600">Card (Swipe/POS)</span>
                  <span className="font-mono">${Number(report.cardSales).toFixed(2)}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-slate-600">Mobile Money / Paynow</span>
                  <span className="font-mono">${Number(report.mobileSales).toFixed(2)}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-slate-600">Credit / Loyalty</span>
                  <span className="font-mono">${Number(report.creditSales).toFixed(2)}</span>
                </div>
                <div className="flex justify-between font-bold text-base pt-2 border-t border-slate-100">
                  <span>Total Tendered</span>
                  <span className="font-mono">
                    ${(Number(report.cashSales) + Number(report.cardSales) + Number(report.mobileSales) + Number(report.creditSales)).toFixed(2)}
                  </span>
                </div>
              </div>
            </div>

            {/* Cash Reconciliation */}
            <div className="bg-slate-50 rounded-lg border border-slate-200 p-4">
              <h3 className="text-sm font-bold uppercase tracking-wider text-slate-500 border-b border-slate-200 pb-2 mb-3">Cash Reconciliation</h3>
              <div className="space-y-2">
                <div className="flex justify-between text-sm">
                  <span className="text-slate-700">Opening Balance</span>
                  <span className="font-mono">${Number(report.session.openingBalance).toFixed(2)}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-slate-700">+ Cash Sales (Net of Change)</span>
                  <span className="font-mono">${Number(report.cashSales).toFixed(2)}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-slate-700">- Cash Voided (Refunds)</span>
                  <span className="font-mono">-${Number(report.totalRefunds).toFixed(2)}</span>
                </div>
                <div className="flex justify-between font-bold text-sm pt-2 border-t border-slate-200">
                  <span>Expected Cash in Drawer</span>
                  <span className="font-mono">${Number(report.expectedCash).toFixed(2)}</span>
                </div>
                <div className="flex justify-between font-bold text-sm">
                  <span>Actual Cash Counted</span>
                  <span className="font-mono">${Number(report.actualCash).toFixed(2)}</span>
                </div>
                <div className="flex justify-between font-bold text-base pt-2 mt-2 border-t-2 border-slate-300">
                  <span>Overage / (Shortage)</span>
                  <span className={`font-mono ${Number(report.cashDifference) < 0 ? 'text-red-600' : Number(report.cashDifference) > 0 ? 'text-emerald-600' : 'text-slate-900'}`}>
                    {Number(report.cashDifference) > 0 ? '+' : ''}${Number(report.cashDifference).toFixed(2)}
                  </span>
                </div>
              </div>
            </div>
          </div>
          
          <div className="mt-12 text-center text-xs text-slate-400 font-mono">
            <p>End of Report</p>
            <p>***</p>
          </div>
        </div>
      </Card>
    </div>
  );
}
