'use client';

import { toast } from '@/components/ui/toast';
import { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Table, TableHeader, TableBody, TableHead, TableRow, TableCell } from '@/components/ui/table';
import { Badge } from '@/components/ui/badge';
import { FileText, Download, Truck, CreditCard, Wrench, Calendar, Droplets, TrendingUp, BarChart3 } from 'lucide-react';
import { useReportExport } from '@/hooks/use-report-export';

interface FleetMetrics {
  totalVehicles: number;
  totalServiceCosts: number;
  totalPrepaidDiesel: number;
  totalPrepaidPetrol: number;
  totalFuelIssued: number;
  trips: { totalTrips: number; activeTrips: number; completedTrips: number };
}

interface FuelAnalytics {
  totalUsed: number;
  totalCost: number;
  avgCostPerLitre: number;
  byType: { diesel: { quantity: number; cost: number }; petrol: { quantity: number; cost: number } };
  byMonth: [string, { quantity: number; cost: number }][];
  byVehicle: { vehicleId: string; plateNumber: string; make: string; model: string; quantity: number; cost: number; records: number }[];
  autoGenerated: number;
  manual: number;
  totalRecords: number;
}

export default function FleetReportsPage() {
  const { triggerExport, ExportDialog } = useReportExport();
  const [metrics, setMetrics] = useState<FleetMetrics | null>(null);
  const [fuelAnalytics, setFuelAnalytics] = useState<FuelAnalytics | null>(null);
  const [loading, setLoading] = useState(true);
  const [dateFrom, setDateFrom] = useState('2026-01-01');
  const [dateTo, setDateTo] = useState('2026-12-31');

  const fetchMetrics = async () => {
    try {
      const res = await fetch('/api/fleet/reports');
      if (res.ok) {
        const data = await res.json();
        setMetrics(data.metrics);
        setFuelAnalytics(data.fuelAnalytics);
      }
    } catch (_) {
      toast('Failed to load fleet report metrics', 'error');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { fetchMetrics(); }, []);

  const reportsList = [
    { name: 'Prepaid Fuel Audit Ledger', type: 'prepaid_ledger', desc: 'Prepaid top-ups, unit price adjustments, and usage logs' },
    { name: 'Fleet Maintenance Cost Audit', type: 'fleet_maintenance', desc: 'Vehicles repair servicing history, routine diagnostics, and costs' },
    { name: 'Logistics Haulage Deliveries Log', type: 'haulage_history', desc: 'Departure times, arrival times, and cargo details of hauling trips' },
  ];

  const downloadReport = (reportType: string, reportName: string) => {
    const url = new URL(`/api/reports/${reportType}/generate`, window.location.origin);
    if (dateFrom) url.searchParams.set('dateFrom', dateFrom);
    if (dateTo) url.searchParams.set('dateTo', dateTo);
    triggerExport(url.toString(), reportName);
    toast(`Generating "${reportName}"...`, 'success');
  };

  const fmt = (n: number) => n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  const maxFuelMonth = fuelAnalytics ? Math.max(...fuelAnalytics.byMonth.map(([, d]) => d.quantity), 1) : 1;

  if (loading) return <div className="p-6 text-slate-500">Loading metrics...</div>;

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
          <Truck className="h-6 w-6 text-mine-blue-800" />
          Fleet Reports & Analytics
        </h2>
        <p className="text-slate-500 mt-1">Generate fleet asset usage reports, fuel budgets, and hauling performance diagnostics</p>
      </div>

      {/* KPI Stats cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card className="bg-gradient-to-br from-blue-500 to-indigo-600 text-white shadow-md">
          <CardContent className="p-5 space-y-2">
            <p className="text-xs uppercase tracking-wider opacity-75 font-semibold">Total Fleet Size</p>
            <h3 className="text-2xl font-bold font-mono">{metrics?.totalVehicles} Vehicles</h3>
          </CardContent>
        </Card>
        <Card className="bg-gradient-to-br from-violet-500 to-purple-600 text-white shadow-md">
          <CardContent className="p-5 space-y-2">
            <p className="text-xs uppercase tracking-wider opacity-75 font-semibold">Total Service Costs</p>
            <h3 className="text-2xl font-bold font-mono">${Number(metrics?.totalServiceCosts || 0).toLocaleString()}</h3>
          </CardContent>
        </Card>
        <Card className="bg-gradient-to-br from-emerald-500 to-teal-600 text-white shadow-md">
          <CardContent className="p-5 space-y-2">
            <p className="text-xs uppercase tracking-wider opacity-75 font-semibold">Prepaid Fuel Left</p>
            <h3 className="text-xl font-bold font-mono">D: {Number(metrics?.totalPrepaidDiesel).toLocaleString()}L</h3>
            <h3 className="text-xl font-bold font-mono">P: {Number(metrics?.totalPrepaidPetrol).toLocaleString()}L</h3>
          </CardContent>
        </Card>
        <Card className="bg-gradient-to-br from-amber-500 to-orange-600 text-white shadow-md">
          <CardContent className="p-5 space-y-2">
            <p className="text-xs uppercase tracking-wider opacity-75 font-semibold">Hauling Deliveries</p>
            <h3 className="text-2xl font-bold font-mono">{metrics?.trips.completedTrips} / {metrics?.trips.totalTrips}</h3>
            <span className="text-[10px] bg-white/20 px-2 py-0.5 rounded font-medium">{metrics?.trips.activeTrips} in transit</span>
          </CardContent>
        </Card>
      </div>

      {/* Fuel Logs Analytics */}
      {fuelAnalytics && (
        <div className="space-y-4">
          <h3 className="text-lg font-bold text-slate-800 flex items-center gap-2">
            <Droplets className="h-5 w-5 text-amber-500" />
            Fuel Consumption Analytics
          </h3>

          {/* Fuel KPI Cards */}
          <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
            <Card className="border border-slate-100">
              <CardContent className="p-3 text-center">
                <p className="text-[10px] text-slate-500 uppercase">Total Fuel Used</p>
                <p className="text-lg font-bold text-slate-800">{fmt(fuelAnalytics.totalUsed)} L</p>
              </CardContent>
            </Card>
            <Card className="border border-slate-100">
              <CardContent className="p-3 text-center">
                <p className="text-[10px] text-slate-500 uppercase">Total Fuel Cost</p>
                <p className="text-lg font-bold text-slate-800">${fmt(fuelAnalytics.totalCost)}</p>
              </CardContent>
            </Card>
            <Card className="border border-slate-100">
              <CardContent className="p-3 text-center">
                <p className="text-[10px] text-slate-500 uppercase">Avg Cost/Litre</p>
                <p className="text-lg font-bold text-slate-800">${fmt(fuelAnalytics.avgCostPerLitre)}</p>
              </CardContent>
            </Card>
            <Card className="border border-slate-100">
              <CardContent className="p-3 text-center">
                <p className="text-[10px] text-slate-500 uppercase">Diesel Used</p>
                <p className="text-lg font-bold text-blue-700">{fmt(fuelAnalytics.byType.diesel.quantity)} L</p>
                <p className="text-[10px] text-slate-400">${fmt(fuelAnalytics.byType.diesel.cost)}</p>
              </CardContent>
            </Card>
            <Card className="border border-slate-100">
              <CardContent className="p-3 text-center">
                <p className="text-[10px] text-slate-500 uppercase">Petrol Used</p>
                <p className="text-lg font-bold text-emerald-700">{fmt(fuelAnalytics.byType.petrol.quantity)} L</p>
                <p className="text-[10px] text-slate-400">${fmt(fuelAnalytics.byType.petrol.cost)}</p>
              </CardContent>
            </Card>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {/* Fuel by Month */}
            <Card className="border border-slate-100">
              <CardHeader className="pb-2">
                <CardTitle className="text-sm flex items-center gap-2">
                  <BarChart3 className="h-4 w-4 text-amber-500" />
                  Fuel by Month
                </CardTitle>
              </CardHeader>
              <CardContent className="p-4">
                {fuelAnalytics.byMonth.length === 0 ? (
                  <p className="text-xs text-slate-400 text-center py-6">No data</p>
                ) : (
                  <div className="space-y-1.5">
                    {fuelAnalytics.byMonth.map(([month, d]) => (
                      <div key={month} className="flex items-center gap-2">
                        <span className="text-[10px] text-slate-500 w-16 shrink-0">{month}</span>
                        <div className="flex-1 bg-slate-100 rounded-full h-5 overflow-hidden">
                          <div className="bg-gradient-to-r from-amber-400 to-amber-500 h-full rounded-full flex items-center pl-2" style={{ width: `${(d.quantity / maxFuelMonth) * 100}%` }}>
                            <span className="text-[9px] text-white font-medium">{fmt(d.quantity)} L</span>
                          </div>
                        </div>
                        <span className="text-[10px] text-slate-500 w-20 text-right">${fmt(d.cost)}</span>
                      </div>
                    ))}
                  </div>
                )}
              </CardContent>
            </Card>

            {/* Fuel by Vehicle */}
            <Card className="border border-slate-100">
              <CardHeader className="pb-2">
                <CardTitle className="text-sm flex items-center gap-2">
                  <Truck className="h-4 w-4 text-mine-blue-500" />
                  Fuel by Vehicle
                </CardTitle>
              </CardHeader>
              <CardContent className="p-0">
                {fuelAnalytics.byVehicle.length === 0 ? (
                  <p className="text-xs text-slate-400 text-center py-6">No data</p>
                ) : (
                  <div className="overflow-x-auto">
                    <Table>
                      <TableHeader>
                        <TableRow>
                          <TableHead className="text-[10px]">Vehicle</TableHead>
                          <TableHead className="text-[10px] text-right">Records</TableHead>
                          <TableHead className="text-[10px] text-right">Qty (L)</TableHead>
                          <TableHead className="text-[10px] text-right">Cost ($)</TableHead>
                        </TableRow>
                      </TableHeader>
                      <TableBody>
                        {fuelAnalytics.byVehicle.map(v => (
                          <TableRow key={v.vehicleId}>
                            <TableCell className="text-[11px] font-medium">{v.plateNumber}</TableCell>
                            <TableCell className="text-[11px] text-right">{v.records}</TableCell>
                            <TableCell className="text-[11px] text-right">{fmt(v.quantity)}</TableCell>
                            <TableCell className="text-[11px] text-right">${fmt(v.cost)}</TableCell>
                          </TableRow>
                        ))}
                      </TableBody>
                    </Table>
                  </div>
                )}
              </CardContent>
            </Card>
          </div>

          {/* Source Breakdown */}
          <Card className="border border-slate-100">
            <CardContent className="p-4">
              <div className="flex items-center gap-6">
                <div className="flex items-center gap-2">
                  <div className="h-3 w-3 rounded-full bg-mine-blue-500" />
                  <span className="text-xs text-slate-600">Auto-generated (requisitions): <strong>{fuelAnalytics.autoGenerated}</strong></span>
                </div>
                <div className="flex items-center gap-2">
                  <div className="h-3 w-3 rounded-full bg-slate-300" />
                  <span className="text-xs text-slate-600">Manual entries: <strong>{fuelAnalytics.manual}</strong></span>
                </div>
                <div className="flex items-center gap-2">
                  <span className="text-xs text-slate-400">Total records: <strong>{fuelAnalytics.totalRecords}</strong></span>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      )}

      {/* Report Parameters */}
      <Card>
        <CardHeader className="pb-3 border-b border-slate-100">
          <CardTitle className="text-sm font-semibold text-slate-700 flex items-center gap-2">
            <Calendar className="h-4 w-4 text-slate-400" />
            Report Parameters
          </CardTitle>
        </CardHeader>
        <CardContent className="p-4 grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div>
            <label className="text-xs font-bold text-slate-500 uppercase tracking-wider block mb-1">From Date</label>
            <input type="date" value={dateFrom} onChange={(e) => setDateFrom(e.target.value)} className="w-full text-sm border border-slate-200 rounded-md px-2 py-1.5 focus:outline-none focus:ring-2 focus:ring-mine-blue-500 text-slate-700" />
          </div>
          <div>
            <label className="text-xs font-bold text-slate-500 uppercase tracking-wider block mb-1">To Date</label>
            <input type="date" value={dateTo} onChange={(e) => setDateTo(e.target.value)} className="w-full text-sm border border-slate-200 rounded-md px-2 py-1.5 focus:outline-none focus:ring-2 focus:ring-mine-blue-500 text-slate-700" />
          </div>
        </CardContent>
      </Card>

      {/* Reports Table */}
      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="text-lg flex items-center gap-2">
            <FileText className="h-5 w-5 text-mine-blue-800" />
            Fleet & Fuel Audit Reports List
          </CardTitle>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Report Name</TableHead>
                <TableHead>Description</TableHead>
                <TableHead className="text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {reportsList.map((report) => (
                <TableRow key={report.type}>
                  <TableCell className="font-semibold text-slate-800">{report.name}</TableCell>
                  <TableCell className="text-xs text-slate-500">{report.desc}</TableCell>
                  <TableCell className="text-right">
                    <Button size="sm" variant="default" onClick={() => downloadReport(report.type, report.name)} className="text-xs gap-1">
                      <Download className="h-3 w-3" />
                      Generate
                    </Button>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
      {ExportDialog}
    </div>
  );
}
