'use client';

import { useState, useEffect } from 'react';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from '@/components/ui/table';
import { Search, Eye, FileText, ArrowRight } from 'lucide-react';
import Link from 'next/link';

interface ZReport {
  id: string;
  reportNumber: string;
  generatedAt: string;
  generatedBy: string;
  totalSales: string;
  actualCash: string;
  cashDifference: string;
  branch?: { name: string } | null;
}

export default function ZReportsPage() {
  const [reports, setReports] = useState<ZReport[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');

  useEffect(() => {
    fetchReports();
  }, []);

  const fetchReports = async (query = '') => {
    setLoading(true);
    try {
      const res = await fetch(`/api/pos/reports/z-reports?search=${encodeURIComponent(query)}`);
      if (res.ok) {
        const data = await res.json();
        setReports(data.items || []);
      }
    } catch (error) {
      console.error('Failed to fetch reports:', error);
    }
    setLoading(false);
  };

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault();
    fetchReports(search);
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-800">Z Reports (End of Day)</h1>
          <p className="text-sm text-slate-500">View and manage POS session closing reports</p>
        </div>
      </div>

      <Card>
        <CardHeader className="border-b border-slate-100 pb-4">
          <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
            <CardTitle className="text-lg font-semibold text-slate-800 flex items-center gap-2">
              <FileText className="h-5 w-5 text-mine-blue-600" />
              Generated Reports
            </CardTitle>
            <form onSubmit={handleSearch} className="flex gap-2 w-full md:w-auto">
              <div className="relative flex-1 md:w-64">
                <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-slate-400" />
                <Input
                  type="text"
                  placeholder="Search report # or cashier..."
                  className="pl-9 bg-slate-50 border-slate-200"
                  value={search}
                  onChange={(e) => setSearch(e.target.value)}
                />
              </div>
              <Button type="submit" variant="secondary">Search</Button>
            </form>
          </div>
        </CardHeader>
        <CardContent className="p-0">
          <div className="overflow-x-auto">
            <Table>
              <TableHeader className="bg-slate-50">
                <TableRow>
                  <TableHead className="font-semibold text-slate-600">Report Number</TableHead>
                  <TableHead className="font-semibold text-slate-600">Date Generated</TableHead>
                  <TableHead className="font-semibold text-slate-600">Generated By</TableHead>
                  <TableHead className="font-semibold text-slate-600 text-right">Total Sales</TableHead>
                  <TableHead className="font-semibold text-slate-600 text-right">Actual Cash</TableHead>
                  <TableHead className="font-semibold text-slate-600 text-right">Difference</TableHead>
                  <TableHead className="w-[100px]"></TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {loading ? (
                  <TableRow>
                    <TableCell colSpan={7} className="h-32 text-center text-slate-500">
                      <div className="flex justify-center items-center">
                        <div className="animate-spin rounded-full h-6 w-6 border-b-2 border-mine-blue-600"></div>
                      </div>
                    </TableCell>
                  </TableRow>
                ) : reports.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={7} className="h-32 text-center text-slate-500">
                      No Z reports found.
                    </TableCell>
                  </TableRow>
                ) : (
                  reports.map((report) => (
                    <TableRow key={report.id} className="hover:bg-slate-50/50">
                      <TableCell className="font-medium text-slate-900">
                        {report.reportNumber}
                      </TableCell>
                      <TableCell className="text-slate-600">
                        {new Date(report.generatedAt).toLocaleString()}
                      </TableCell>
                      <TableCell className="text-slate-600">
                        {report.generatedBy}
                        {report.branch && <span className="block text-xs text-slate-400">{report.branch.name}</span>}
                      </TableCell>
                      <TableCell className="text-right font-mono font-medium text-slate-700">
                        ${Number(report.totalSales).toFixed(2)}
                      </TableCell>
                      <TableCell className="text-right font-mono text-slate-600">
                        ${Number(report.actualCash).toFixed(2)}
                      </TableCell>
                      <TableCell className="text-right font-mono">
                        {Number(report.cashDifference) < 0 ? (
                          <span className="text-red-600 font-semibold">-${Math.abs(Number(report.cashDifference)).toFixed(2)}</span>
                        ) : Number(report.cashDifference) > 0 ? (
                          <span className="text-emerald-600 font-semibold">+${Number(report.cashDifference).toFixed(2)}</span>
                        ) : (
                          <span className="text-slate-400">$0.00</span>
                        )}
                      </TableCell>
                      <TableCell className="text-right">
                        <Link href={`/pos/reports/z-reports/${report.id}`}>
                          <Button variant="ghost" size="sm" className="h-8 text-mine-blue-600 hover:text-mine-blue-700 hover:bg-mine-blue-50">
                            View <ArrowRight className="ml-1.5 h-3.5 w-3.5" />
                          </Button>
                        </Link>
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
