import { NextRequest } from 'next/server';
import { getSession, unauthorized } from '@/lib/api';

export async function POST(request: NextRequest, { params }: { params: Promise<{ type: string }> }) {
  const session = await getSession();
  if (!session) return unauthorized();

  const { type } = await params;
  const name = type.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());

  const html = `<html><body><h1>${name}</h1><p>Generated by Mineazy ERP</p><p>Report type: ${type}</p><p>Generated at: ${new Date().toISOString()}</p></body></html>`;

  return new Response(html, {
    headers: {
      'Content-Type': 'text/html',
      'Content-Disposition': `attachment; filename="${type}.html"`,
    },
  });
}
