import { NextRequest } from 'next/server';
import { prisma } from '@/lib/prisma';
import { getSession, unauthorized, ok } from '@/lib/api';

export async function GET(request: NextRequest) {
  const session = await getSession();
  if (!session) return unauthorized();

  const totalVehicles = await prisma.erpVehicle.count();
  const totalServiceCostsAgg = await prisma.erpServiceRecord.aggregate({
    _sum: { cost: true }
  });
  const totalServiceCosts = Number(totalServiceCostsAgg._sum.cost || 0);

  const prepaidFuels = await prisma.erpPrepaidFuel.findMany();
  const totalPrepaidDiesel = Number(prepaidFuels.find(f => f.fuelType === 'Diesel')?.balanceLiters || 0);
  const totalPrepaidPetrol = Number(prepaidFuels.find(f => f.fuelType === 'Petrol')?.balanceLiters || 0);

  const fuelIssuedAgg = await prisma.erpFuelRequisition.aggregate({
    where: { status: 'APPROVED' },
    _sum: { litersRequested: true }
  });
  const totalFuelIssued = Number(fuelIssuedAgg._sum.litersRequested || 0);

  const totalTrips = await prisma.erpHaulingTrip.count();
  const activeTrips = await prisma.erpHaulingTrip.count({ where: { status: 'IN_TRANSIT' } });
  const completedTrips = await prisma.erpHaulingTrip.count({ where: { status: 'DELIVERED' } });

  const usageLogs = await prisma.erpPrepaidFuelLog.findMany({
    orderBy: { createdAt: 'desc' },
    take: 10
  });

  // --- Fuel Logs Analytics ---
  const fuelRecords = await prisma.erpFuelRecord.findMany({
    include: { vehicle: { select: { id: true, plateNumber: true, make: true, model: true } } },
    orderBy: { refuelDate: 'desc' },
  });

  const totalFuelUsed = fuelRecords.reduce((s, r) => s + Number(r.quantity), 0);
  const totalFuelCost = fuelRecords.reduce((s, r) => s + Number(r.totalCost), 0);

  // By fuel type
  const dieselRecords = fuelRecords.filter(r => r.fuelType === 'Diesel');
  const petrolRecords = fuelRecords.filter(r => r.fuelType === 'Petrol');
  const dieselUsed = dieselRecords.reduce((s, r) => s + Number(r.quantity), 0);
  const dieselCost = dieselRecords.reduce((s, r) => s + Number(r.totalCost), 0);
  const petrolUsed = petrolRecords.reduce((s, r) => s + Number(r.quantity), 0);
  const petrolCost = petrolRecords.reduce((s, r) => s + Number(r.totalCost), 0);

  // By month
  const fuelByMonth: Record<string, { quantity: number; cost: number }> = {};
  for (const r of fuelRecords) {
    const key = new Date(r.refuelDate).toISOString().slice(0, 7);
    if (!fuelByMonth[key]) fuelByMonth[key] = { quantity: 0, cost: 0 };
    fuelByMonth[key].quantity += Number(r.quantity);
    fuelByMonth[key].cost += Number(r.totalCost);
  }

  // By vehicle
  const fuelByVehicle: Record<string, { plateNumber: string; make: string; model: string; quantity: number; cost: number; records: number }> = {};
  for (const r of fuelRecords) {
    const vId = r.vehicleId;
    if (!fuelByVehicle[vId]) {
      fuelByVehicle[vId] = { plateNumber: r.vehicle?.plateNumber || '—', make: r.vehicle?.make || '', model: r.vehicle?.model || '', quantity: 0, cost: 0, records: 0 };
    }
    fuelByVehicle[vId].quantity += Number(r.quantity);
    fuelByVehicle[vId].cost += Number(r.totalCost);
    fuelByVehicle[vId].records++;
  }
  const fuelByVehicleSorted = Object.entries(fuelByVehicle)
    .map(([vehicleId, data]) => ({ vehicleId, ...data }))
    .sort((a, b) => b.quantity - a.quantity);

  // Average cost per litre
  const avgCostPerLitre = totalFuelUsed > 0 ? totalFuelCost / totalFuelUsed : 0;

  // Auto vs manual
  const autoRecords = fuelRecords.filter(r => r.notes?.includes('Auto from requisition'));
  const manualRecords = fuelRecords.filter(r => !r.notes?.includes('Auto from requisition'));

  return ok({
    metrics: {
      totalVehicles,
      totalServiceCosts,
      totalPrepaidDiesel,
      totalPrepaidPetrol,
      totalFuelIssued,
      trips: { totalTrips, activeTrips, completedTrips }
    },
    logs: usageLogs,
    fuelAnalytics: {
      totalUsed: totalFuelUsed,
      totalCost: totalFuelCost,
      avgCostPerLitre,
      byType: {
        diesel: { quantity: dieselUsed, cost: dieselCost },
        petrol: { quantity: petrolUsed, cost: petrolCost },
      },
      byMonth: Object.entries(fuelByMonth).sort(([a], [b]) => a.localeCompare(b)),
      byVehicle: fuelByVehicleSorted,
      autoGenerated: autoRecords.length,
      manual: manualRecords.length,
      totalRecords: fuelRecords.length,
    }
  });
}
